import "server-only";
import { randomUUID } from "node:crypto";

type PresentationRecord = { id: string; name: string; size_bytes: number; mime_type: string; created_at: string; storage_path: string };
function config() { const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const key = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !key) throw new Error("Storage configuration is unavailable."); return { url, headers: { apikey: key, Authorization: `Bearer ${key}` } }; }
async function request(path: string, init?: RequestInit) { const { url, headers } = config(); const response = await fetch(`${url}${path}`, { ...init, headers: { ...headers, ...init?.headers } }); if (!response.ok) throw new Error("Supabase request failed."); return response; }
export async function listPresentations() { return (await request("/rest/v1/presentation_files?select=id,name,size_bytes,mime_type,created_at&order=created_at.desc")).json() as Promise<Omit<PresentationRecord, "storage_path">[]>; }
export async function uploadPresentation(file: File, extension: "ppt" | "pptx") { const storagePath = `${randomUUID()}.${extension}`; await request(`/storage/v1/object/presentations/${storagePath}`, { method: "POST", headers: { "content-type": file.type, "x-upsert": "false" }, body: await file.arrayBuffer() }); try { return (await request("/rest/v1/presentation_files", { method: "POST", headers: { "content-type": "application/json", Prefer: "return=representation" }, body: JSON.stringify({ name: file.name, storage_path: storagePath, mime_type: file.type, size_bytes: file.size }) })).json().then((items: Omit<PresentationRecord, "storage_path">[]) => items[0]); } catch (error) { await request("/storage/v1/object/presentations", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ prefixes: [storagePath] }) }).catch(() => undefined); throw error; } }
async function record(id: string) { const values = await request(`/rest/v1/presentation_files?select=id,name,storage_path&id=eq.${encodeURIComponent(id)}&limit=1`).then((response) => response.json() as Promise<Pick<PresentationRecord, "id" | "name" | "storage_path">[]>); if (!values[0]) throw new Error("Presentation not found."); return values[0]; }
export async function downloadPresentation(id: string) { const item = await record(id); const result = await request(`/storage/v1/object/sign/presentations/${item.storage_path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ expiresIn: 300, download: item.name }) }).then((response) => response.json() as Promise<{ signedURL: string }>); return `${config().url}/storage/v1${result.signedURL}`; }
export async function deletePresentation(id: string) { const item = await record(id); await request("/storage/v1/object/presentations", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ prefixes: [item.storage_path] }) }); await request(`/rest/v1/presentation_files?id=eq.${encodeURIComponent(id)}`, { method: "DELETE" }); }
